### ISSUE TITLE
a question about expression " interrupts = /bits/ 8 <17 0xc>; "

### ISSUE THREAD

**Issue by chankim** [vagrantc/device-tree-compiler#1]
Hi, this is just a question (maybe request for clarification in the document?)
Does this mean when it is compiled to a dtb file, the value is in 8 bit form? both 17 and 0xc?
Eventualy an OS should interpret the dtb(or fdt), then, does the dtb format contain the format information about this variable? (whether it's 32 bit or 8 bit data).
Thank you.

**Comment by vagrantc** [comment]
you might want to take this issue upstream, this is just a very old fork of the device-tree-compiler project, not actively developed.
